server:
  port: 9097
spring:
  main:
    allow-circular-references: true
  application:
    name: web-01
  datasource:
    url: jdbc:mysql://localhost:3306/todo_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: omeR%50hajk
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: omer
      password: password
      roles: ADMIN, MANAGER, USER


management:
  endpoints:
    web:
      exposure:
        include: '*'